// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

package network.tork.governance.pii;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public final class PiiRegistry {
    public static final String VERSION = "1.2.0";
    public static final String CONTENT_HASH = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26";

    /** The keyword gate is ASYMMETRIC — see README.md, rule 3. */
    public static final int KEYWORD_WINDOW_BEFORE = 60;
    public static final int KEYWORD_WINDOW_AFTER = 40;
    public static final int CONTEXT_WINDOW = 60;
    public static final int LABEL_WINDOW = 60;
    public static final int LABEL_REACH = 25;

    public static final String NEAR_MISS_REDACTION = "[NATIONAL_ID_REDACTED]";
    public static final String NEAR_MISS_TYPE = "national_id_near_miss";
    public static final List<String> NEAR_MISS_KINDS = list("health_id", "national_id", "tax_id");

    public static final List<String> TABLE_DELIMITERS = list("\t", "|", ";", ",");
    public static final int TABLE_MAX_HEADER_LENGTH = 32;
    public static final int TABLE_MAX_HEADER_WORDS = 4;
    public static final int TABLE_MIN_ROWS = 3;
    public static final int TABLE_MIN_COMMA_COLUMNS = 3;

    /** Java 11 has no List.of overload past ten arguments that reads well here, and varargs keeps every list identical in shape. */
    private static List<String> list(String... values) {
        return Collections.unmodifiableList(Arrays.asList(values));
    }

    public static final List<String> LABELS = list(
        "AADHAAR",
        "ABN",
        "ACN",
        "BVN",
        "CA_PASSPORT",
        "CA_PHONE",
        "CA_POSTAL",
        "CNIC",
        "CNPJ",
        "CODICE_FISCALE",
        "CPF",
        "EMIRATES_ID",
        "GHANA_CARD",
        "IFSC",
        "ITIN",
        "KRA_PIN",
        "MEDICARE",
        "MYKAD",
        "MY_NUMBER",
        "NATIONAL_ID",
        "NHS",
        "NIK",
        "NIN",
        "NINO",
        "NRIC",
        "PAN",
        "PASSPORT",
        "PHONE",
        "PINCODE",
        "PO_BOX",
        "RESIDENT_ID",
        "RFC",
        "RRN",
        "SIN",
        "SORT_CODE",
        "TAN",
        "TAX_ID",
        "TFN",
        "UK_POSTCODE",
        "ZA_ID"
    );

    public static final List<String> REFERENCE_LABELS = list(
        "order",
        "invoice",
        "purchase order",
        "po no",
        "po number",
        "job number",
        "job no",
        "booking",
        "tracking",
        "consignment",
        "waybill",
        "airway bill",
        "awb",
        "docket",
        "quote",
        "quotation",
        "ticket",
        "receipt",
        "serial number",
        "asset tag",
        "part number",
        "stock code",
        "batch",
        "shipment",
        "dispatch note",
        "delivery note",
        "work order",
        "contract number",
        "policy number",
        "meter number",
        "case id",
        "bestelling",
        "bestelnommer",
        "faktuur",
        "kwotasie",
        "commande",
        "facture",
        "devis",
        "bon de livraison",
        "expédition",
        "expedition",
        "pedido",
        "fatura",
        "factura",
        "orçamento",
        "orcamento",
        "presupuesto",
        "remito",
        "pesanan",
        "nombor pesanan",
        "invois",
        "sebut harga",
        "penghantaran",
        "resit",
        "आदेश",
        "क्रय आदेश",
        "चालान",
        "कोटेशन",
        "रसीद",
        "آرڈر",
        "انوائس",
        "رسید",
        "کوٹیشن",
        "ترسیل",
        "طلب",
        "أمر شراء",
        "فاتورة",
        "عرض سعر",
        "إيصال",
        "شحنة",
        "بوليصة",
        "注文",
        "注文番号",
        "発注",
        "発注番号",
        "請求書",
        "請求番号",
        "伝票",
        "伝票番号",
        "見積",
        "見積番号",
        "管理番号",
        "在庫番号",
        "受注",
        "出荷",
        "订单",
        "訂單",
        "订单编号",
        "訂單編號",
        "发票",
        "發票",
        "采购",
        "採購",
        "报价",
        "報價",
        "运单",
        "運單",
        "物料编号",
        "物料編號",
        "库存",
        "庫存",
        "주문",
        "주문번호",
        "구매주문",
        "송장",
        "견적",
        "견적서",
        "운송장",
        "자재번호",
        "재고번호",
        "ใบสั่งซื้อ",
        "เลขที่ใบสั่งซื้อ",
        "ใบแจ้งหนี้",
        "ใบเสนอราคา",
        "ใบส่งของ",
        "รหัสพัสดุ",
        "ใบงาน"
    );

    public static final List<String> GENERIC_ID_KEYWORDS = list(
        "national id",
        "national identity",
        "national identification",
        "national number",
        "national code",
        "identity number",
        "identification number",
        "id number",
        "citizen id",
        "citizen number",
        "resident id",
        "resident number",
        "civil id",
        "civil number",
        "civil registration",
        "personal number",
        "personal identity",
        "personal code",
        "personal id",
        "tax identification",
        "tax reference",
        "taxpayer number",
        "taxpayer id"
    );

    public static final List<String> LOCAL_ID_KEYWORDS = list(
        "cedula",
        "cédula",
        "iqama",
        "nadra",
        "cnic",
        "aadhaar",
        "voen",
        "vöen",
        "егн",
        "oib",
        "cpr-nummer",
        "cpr nummer",
        "kennitala",
        "personnummer",
        "adoazonosito",
        "adóazonosító",
        "szemelyi azonosito",
        "személyi azonosító",
        "kimlik",
        "рнокпп",
        "nid number",
        "sars income tax"
    );

    /** Java 11: a final class with final fields, not a record. */
    public static final class Country {
        public final String code;
        public final String name;
        public final String callingCode;
        public final boolean bloc;
        public final List<String> patterns;

        Country(String code, String name, String callingCode, boolean bloc, List<String> patterns) {
            this.code = code;
            this.name = name;
            this.callingCode = callingCode;
            this.bloc = bloc;
            this.patterns = patterns;
        }

        public String code() { return code; }
        public String name() { return name; }
        public String callingCode() { return callingCode; }
        public boolean bloc() { return bloc; }
        public List<String> patterns() { return patterns; }
    }

    public static final class Pattern {
        public final String name;
        public final String country;
        public final String kind;
        public final String regex;
        public final String redaction;
        public final String type;
        public final String label;
        public final boolean requiresKeyword;
        public final boolean alwaysOn;
        public final List<String> keywords;
        public final List<String> wholeWordKeywords;
        public final List<String> nearMissKeywords;
        public final boolean nearMissFallback;
        public final String checksum;
        public final boolean checksumRequired;

        Pattern(String name, String country, String kind, String regex, String redaction, String type,
                String label, boolean requiresKeyword, boolean alwaysOn, List<String> keywords, List<String> wholeWordKeywords,
                List<String> nearMissKeywords, boolean nearMissFallback, String checksum, boolean checksumRequired) {
            this.name = name;
            this.country = country;
            this.kind = kind;
            this.regex = regex;
            this.redaction = redaction;
            this.type = type;
            this.label = label;
            this.requiresKeyword = requiresKeyword;
            this.alwaysOn = alwaysOn;
            this.keywords = keywords;
            this.wholeWordKeywords = wholeWordKeywords;
            this.nearMissKeywords = nearMissKeywords;
            this.nearMissFallback = nearMissFallback;
            this.checksum = checksum;
            this.checksumRequired = checksumRequired;
        }

        public String name() { return name; }
        public String country() { return country; }
        public String kind() { return kind; }
        public String regex() { return regex; }
        public String redaction() { return redaction; }
        public String type() { return type; }
        public String label() { return label; }
        public boolean requiresKeyword() { return requiresKeyword; }
        public boolean alwaysOn() { return alwaysOn; }
        public List<String> keywords() { return keywords; }
        public List<String> wholeWordKeywords() { return wholeWordKeywords; }
        public List<String> nearMissKeywords() { return nearMissKeywords; }
        public boolean nearMissFallback() { return nearMissFallback; }
        public String checksum() { return checksum; }
        public boolean checksumRequired() { return checksumRequired; }
    }

    public static final class Signal {
        public final String country;
        public final String regex;
        public final String flags;
        public final List<String> keywords;
        public final List<String> wholeWordKeywords;
        public final String activates;

        Signal(String country, String regex, String flags, List<String> keywords,
               List<String> wholeWordKeywords, String activates) {
            this.country = country;
            this.regex = regex;
            this.flags = flags;
            this.keywords = keywords;
            this.wholeWordKeywords = wholeWordKeywords;
            this.activates = activates;
        }

        public String country() { return country; }
        public String regex() { return regex; }
        public String flags() { return flags; }
        public List<String> keywords() { return keywords; }
        public List<String> wholeWordKeywords() { return wholeWordKeywords; }
        public String activates() { return activates; }
    }

    public static final List<Country> COUNTRIES = Collections.unmodifiableList(Arrays.asList(
        new Country("AU", "Australia", "61", false, list("au_tfn", "au_abn", "au_medicare", "au_acn", "au_phone_intl")),
        new Country("US", "United States", "1", false, list("us_itin", "us_passport_alpha")),
        new Country("GB", "United Kingdom", "44", false, list("uk_phone_full", "uk_sort_code", "uk_nino", "uk_nhs", "uk_postcode")),
        new Country("EU", "European Union", "", true, list("de_tax_id")),
        new Country("AE", "United Arab Emirates", "971", false, list("emirates_id", "uae_phone", "uae_landline", "po_box")),
        new Country("SA", "Saudi Arabia", "966", false, list("sa_national_id", "sa_phone")),
        new Country("NG", "Nigeria", "234", false, list("ng_nin", "ng_bvn", "ng_phone")),
        new Country("IN", "India", "91", false, list("in_aadhaar", "in_pan", "in_phone", "in_ifsc", "in_pincode")),
        new Country("JP", "Japan", "81", false, list("jp_my_number", "jp_phone_intl", "jp_phone_national")),
        new Country("CN", "China", "86", false, list("cn_resident_id", "cn_phone_intl", "cn_phone_national")),
        new Country("KR", "South Korea", "82", false, list("kr_rrn", "kr_phone_intl", "kr_phone_national")),
        new Country("BR", "Brazil", "55", false, list("br_cpf", "br_cnpj")),
        new Country("CA", "Canada", "1", false, list("ca_sin", "ca_phone", "ca_postal_code", "ca_passport")),
        new Country("ZA", "South Africa", "27", false, list("za_id_number", "za_phone")),
        new Country("GH", "Ghana", "233", false, list("gh_ghana_card")),
        new Country("IT", "Italy", "39", false, list("it_codice_fiscale")),
        new Country("KE", "Kenya", "254", false, list("ke_kra_pin")),
        new Country("MU", "Mauritius", "230", false, list("mu_tan")),
        new Country("MX", "Mexico", "52", false, list("mx_rfc")),
        new Country("MY", "Malaysia", "60", false, list("my_mykad")),
        new Country("PK", "Pakistan", "92", false, list("pk_cnic")),
        new Country("SG", "Singapore", "65", false, list("sg_nric")),
        new Country("TH", "Thailand", "66", false, list("th_national_id")),
        new Country("ID", "Indonesia", "62", false, list("id_nik"))
    ));

    public static final List<Pattern> PATTERNS = Collections.unmodifiableList(Arrays.asList(
        new Pattern("au_tfn", "AU", "tax_id",
            "\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b",
            "[TFN_REDACTED]", "au_tfn", "TFN", true, true,
            list("tfn", "tax file", "tax number"),
            list(),
            list(),
            true, "au_tfn", true),
        new Pattern("au_abn", "AU", "company",
            "\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b",
            "[ABN_REDACTED]", "au_abn", "ABN", true, true,
            list("abn", "business number", "australian business"),
            list(),
            list(),
            false, "au_abn", true),
        new Pattern("au_medicare", "AU", "health_id",
            "\\b\\d{4}[ \\t]?\\d{5}[ \\t]?\\d{1}\\b",
            "[MEDICARE_REDACTED]", "au_medicare", "MEDICARE", true, true,
            list("medicare"),
            list(),
            list(),
            false, "au_medicare", false),
        new Pattern("au_acn", "AU", "company",
            "\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b",
            "[ACN_REDACTED]", "au_acn", "ACN", true, false,
            list("acn", "company number", "australian company"),
            list(),
            list(),
            false, null, false),
        new Pattern("au_phone_intl", "AU", "phone",
            "\\+61[ \\t]?[2-478](?:[ \\t]?\\d){8}\\b",
            "[PHONE_REDACTED]", "au_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("us_itin", "US", "tax_id",
            "\\b9\\d{2}-[7-9]\\d-\\d{4}\\b",
            "[ITIN_REDACTED]", "us_itin", "ITIN", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("us_passport_alpha", "US", "passport",
            "\\b[A-Z]\\d{8}\\b",
            "[PASSPORT_REDACTED]", "us_passport", "PASSPORT", true, false,
            list("passport"),
            list(),
            list(),
            false, null, false),
        new Pattern("uk_phone_full", "GB", "phone",
            "(?:\\+44[ \\t]?|\\b0)(?:7\\d{3}|\\d{2,4})[ \\t]?\\d{3,4}[ \\t]?\\d{3,4}\\b",
            "[PHONE_REDACTED]", "uk_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("uk_sort_code", "GB", "bank",
            "\\b\\d{2}-\\d{2}-\\d{2}\\b",
            "[SORT_CODE_REDACTED]", "uk_sort_code", "SORT_CODE", true, false,
            list("sort code", "sort-code", "bank", "account"),
            list(),
            list(),
            false, null, false),
        new Pattern("uk_nino", "GB", "national_id",
            "\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b",
            "[NINO_REDACTED]", "national_id", "NINO", true, false,
            list("national insurance", "ni number", "nino", "ni:", "insurance number"),
            list(),
            list(),
            false, null, false),
        new Pattern("uk_nhs", "GB", "health_id",
            "\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[NHS_REDACTED]", "health_id", "NHS", true, false,
            list("nhs", "national health", "nhs number", "health service"),
            list(),
            list(),
            true, "uk_nhs", true),
        new Pattern("uk_postcode", "GB", "postcode",
            "\\b[A-Z]{1,2}\\d[A-Z\\d]?[ \\t]?\\d[A-Z]{2}\\b",
            "[UK_POSTCODE_REDACTED]", "postal_code", "UK_POSTCODE", true, false,
            list("postcode", "post code", "uk", "united kingdom", "britain", "england", "scotland", "wales"),
            list(),
            list(),
            false, null, false),
        new Pattern("de_tax_id", "EU", "tax_id",
            "\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b",
            "[TAX_ID_REDACTED]", "de_tax_id", "TAX_ID", true, false,
            list("steuer", "tax id", "steuernummer", "idnr", "steueridentifikation"),
            list(),
            list(),
            false, "de_steuer_id", false),
        new Pattern("emirates_id", "AE", "national_id",
            "\\b784-?\\d{4}-?\\d{7}-?\\d\\b",
            "[EMIRATES_ID_REDACTED]", "emirates_id", "EMIRATES_ID", false, false,
            list(),
            list(),
            list(),
            false, "ae_emirates_id", false),
        new Pattern("uae_phone", "AE", "phone",
            "(?:\\+971[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[PHONE_REDACTED]", "uae_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("uae_landline", "AE", "phone",
            "(?:\\+971[ \\t]?|\\b0)[2-4679][ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[PHONE_REDACTED]", "uae_landline", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("po_box", "AE", "postcode",
            "\\b[Pp]\\.?[Oo]\\.?[ \\t]*[Bb]ox[ \\t]+\\d{3,6}\\b",
            "[PO_BOX_REDACTED]", "po_box", "PO_BOX", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("sa_national_id", "SA", "national_id",
            "\\b[12]\\d{9}\\b",
            "[NATIONAL_ID_REDACTED]", "sa_national_id", "NATIONAL_ID", true, false,
            list("national id", "iqama", "national identification", "resident id", "saudi id"),
            list(),
            list(),
            false, "sa_national_id", false),
        new Pattern("sa_phone", "SA", "phone",
            "(?:\\+966[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[PHONE_REDACTED]", "sa_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("ng_nin", "NG", "national_id",
            "\\b\\d{11}\\b",
            "[NIN_REDACTED]", "ng_nin", "NIN", true, false,
            list("nin", "national id", "national identification"),
            list(),
            list(),
            false, null, false),
        new Pattern("ng_bvn", "NG", "bank",
            "\\b\\d{11}\\b",
            "[BVN_REDACTED]", "ng_bvn", "BVN", true, false,
            list("bvn", "bank verification"),
            list(),
            list(),
            false, null, false),
        new Pattern("ng_phone", "NG", "phone",
            "(?:\\+234[ \\t]?|\\b0)[789]0[1-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[PHONE_REDACTED]", "ng_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("in_aadhaar", "IN", "national_id",
            "\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b",
            "[AADHAAR_REDACTED]", "in_aadhaar", "AADHAAR", true, false,
            list("aadhaar", "aadhar", "uid", "unique identification", "aadhaar number"),
            list(),
            list(),
            true, "verhoeff", true),
        new Pattern("in_pan", "IN", "tax_id",
            "\\b[A-Z]{5}\\d{4}[A-Z]\\b",
            "[PAN_REDACTED]", "in_pan", "PAN", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("in_phone", "IN", "phone",
            "(?:\\+91[ \\t]?|\\b0|\\b)[6-9]\\d{4}[ \\t]?\\d{5}\\b",
            "[PHONE_REDACTED]", "in_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("in_ifsc", "IN", "bank",
            "\\b[A-Z]{4}0[A-Z0-9]{6}\\b",
            "[IFSC_REDACTED]", "in_ifsc", "IFSC", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("in_pincode", "IN", "postcode",
            "\\b[1-9]\\d{5}\\b",
            "[PINCODE_REDACTED]", "in_pincode", "PINCODE", true, false,
            list("pin code", "pincode", "postal code", "zip", "address"),
            list(),
            list(),
            false, null, false),
        new Pattern("jp_my_number", "JP", "national_id",
            "\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b",
            "[MY_NUMBER_REDACTED]", "jp_my_number", "MY_NUMBER", true, false,
            list("my number", "individual number", "マイナンバー"),
            list(),
            list(),
            true, "jp_my_number", true),
        new Pattern("jp_phone_intl", "JP", "phone",
            "\\+81[ \\t-]?[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b",
            "[PHONE_REDACTED]", "jp_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("jp_phone_national", "JP", "phone",
            "\\b0[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b",
            "[PHONE_REDACTED]", "jp_phone", "PHONE", true, false,
            list("phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"),
            list(),
            list(),
            false, null, false),
        new Pattern("cn_resident_id", "CN", "national_id",
            "\\b\\d{6}(?:19|20)\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{3}[0-9Xx]\\b",
            "[RESIDENT_ID_REDACTED]", "cn_resident_id", "RESIDENT_ID", true, false,
            list("resident id", "resident identity", "identity card", "id card", "national id", "id number", "id no", "id:", "id =", "identity number", "hukou", "身份证", "身份證", "居民身份证", "居民身份證"),
            list(),
            list(),
            true, "cn_resident_id", true),
        new Pattern("cn_phone_intl", "CN", "phone",
            "\\+86[ \\t-]?1[3-9]\\d{9}\\b",
            "[PHONE_REDACTED]", "cn_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("cn_phone_national", "CN", "phone",
            "\\b1[3-9]\\d{9}\\b",
            "[PHONE_REDACTED]", "cn_phone", "PHONE", true, false,
            list("phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"),
            list(),
            list(),
            false, null, false),
        new Pattern("kr_rrn", "KR", "national_id",
            "\\b\\d{6}-?[1-4]\\d{6}\\b",
            "[RRN_REDACTED]", "kr_rrn", "RRN", true, false,
            list("resident registration", "resident number", "registration number", "rrn", "jumin", "juminbeonho", "national id", "id number", "id no", "id:", "id =", "identity number", "주민등록번호", "주민번호"),
            list(),
            list(),
            false, "kr_rrn", false),
        new Pattern("kr_phone_intl", "KR", "phone",
            "\\+82[ \\t-]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b",
            "[PHONE_REDACTED]", "kr_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("kr_phone_national", "KR", "phone",
            "\\b01[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b",
            "[PHONE_REDACTED]", "kr_phone", "PHONE", true, false,
            list("phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"),
            list(),
            list(),
            false, null, false),
        new Pattern("br_cpf", "BR", "national_id",
            "\\b\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}\\b",
            "[CPF_REDACTED]", "br_cpf", "CPF", false, false,
            list(),
            list(),
            list("cpf", "cadastro de pessoas", "receita federal"),
            true, "br_cpf", true),
        new Pattern("br_cnpj", "BR", "company",
            "\\b\\d{2}\\.?\\d{3}\\.?\\d{3}\\/?\\d{4}-?\\d{2}\\b",
            "[CNPJ_REDACTED]", "br_cnpj", "CNPJ", false, false,
            list(),
            list(),
            list(),
            false, "br_cnpj", true),
        new Pattern("ca_sin", "CA", "national_id",
            "\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b",
            "[SIN_REDACTED]", "ca_sin", "SIN", false, false,
            list("sin", "social insurance", "canada revenue", "cra", "employment insurance"),
            list(),
            list(),
            false, "ca_sin", false),
        new Pattern("ca_phone", "CA", "phone",
            "\\b(\\+?1[-. \\t]?)?\\(?\\d{3}\\)?[-. \\t]\\d{3}[-. \\t]\\d{4}\\b",
            "[CA_PHONE_REDACTED]", "phone", "CA_PHONE", false, false,
            list("phone", "mobile", "cell", "tel"),
            list(),
            list(),
            false, null, false),
        new Pattern("ca_postal_code", "CA", "postcode",
            "\\b[A-Za-z]\\d[A-Za-z][ \\t-]?\\d[A-Za-z]\\d\\b",
            "[CA_POSTAL_REDACTED]", "postal_code", "CA_POSTAL", false, false,
            list("postal", "zip", "post code", "mailing"),
            list(),
            list(),
            false, null, false),
        new Pattern("ca_passport", "CA", "passport",
            "\\b[A-Za-z]{2}\\d{6}\\b",
            "[CA_PASSPORT_REDACTED]", "passport", "CA_PASSPORT", true, false,
            list("passport", "travel document", "citizenship"),
            list(),
            list(),
            false, null, false),
        new Pattern("za_id_number", "ZA", "national_id",
            "\\b(\\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])(\\d{4})(0|1)(\\d{2})\\b",
            "[ZA_ID_REDACTED]", "za_id_number", "ZA_ID", false, false,
            list(),
            list(),
            list("sa id", "rsa id", "south african id", "suid-afrikaanse id", "id no", "id-nommer", "home affairs"),
            true, "za_id", true),
        new Pattern("za_phone", "ZA", "phone",
            "(?:\\+27[ \\t]?|\\b0)[6-8]\\d[ \\t]?\\d{3}[ \\t]?\\d{4}\\b",
            "[PHONE_REDACTED]", "za_phone", "PHONE", false, false,
            list(),
            list(),
            list(),
            false, null, false),
        new Pattern("gh_ghana_card", "GH", "national_id",
            "\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b",
            "[GHANA_CARD_REDACTED]", "gh_ghana_card", "GHANA_CARD", true, false,
            list("ghana card", "ghanacard", "ghana revenue", "nia pin", "personal id number", "gra tin"),
            list(),
            list(),
            false, null, false),
        new Pattern("it_codice_fiscale", "IT", "tax_id",
            "\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b",
            "[CODICE_FISCALE_REDACTED]", "it_codice_fiscale", "CODICE_FISCALE", true, false,
            list("codice fiscale", "cod. fisc", "cod.fisc", "c.f.", "anagrafe tributaria", "tessera sanitaria"),
            list(),
            list(),
            true, "it_codice_fiscale", true),
        new Pattern("ke_kra_pin", "KE", "tax_id",
            "\\b[AP]\\d{9}[A-Z]\\b",
            "[KRA_PIN_REDACTED]", "ke_kra_pin", "KRA_PIN", true, false,
            list("kra pin", "kra", "tax pin", "itax", "pin certificate", "personal identification number"),
            list(),
            list(),
            false, null, false),
        new Pattern("mu_tan", "MU", "tax_id",
            "\\b[123578]\\d{7}\\b",
            "[TAN_REDACTED]", "mu_tan", "TAN", true, false,
            list("tax account number", "mauritius revenue", "tan ", "tan:", "tan no", "tan number", "mra tan"),
            list(),
            list(),
            false, null, false),
        new Pattern("mx_rfc", "MX", "tax_id",
            "\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b",
            "[RFC_REDACTED]", "mx_rfc", "RFC", true, false,
            list("rfc", "homoclave", "registro federal de contribuyentes", "contribuyentes", "constancia de situación fiscal"),
            list(),
            list(),
            false, null, false),
        new Pattern("my_mykad", "MY", "national_id",
            "\\b\\d{6}-?\\d{2}-?\\d{4}\\b",
            "[MYKAD_REDACTED]", "my_mykad", "MYKAD", true, false,
            list("mykad", "my kad", "kad pengenalan", "no. kad pengenalan", "nric", "ic number", "no. ic", "mykid"),
            list(),
            list(),
            false, null, false),
        new Pattern("pk_cnic", "PK", "national_id",
            "\\b\\d{5}-?\\d{7}-?\\d\\b",
            "[CNIC_REDACTED]", "pk_cnic", "CNIC", true, false,
            list("cnic", "nadra", "nic number", "identity card number", "شناختی کارڈ", "شناختی"),
            list(),
            list(),
            false, null, false),
        new Pattern("sg_nric", "SG", "national_id",
            "\\b[STFGM]\\d{7}[A-Z]\\b",
            "[NRIC_REDACTED]", "sg_nric", "NRIC", true, false,
            list("nric", "fin number", "fin no", "fin:", "identity card", "identification number", "cpf", "singpass"),
            list(),
            list(),
            true, "sg_nric", true),
        new Pattern("th_national_id", "TH", "national_id",
            "\\b\\d-?\\d{4}-?\\d{5}-?\\d{2}-?\\d\\b",
            "[NATIONAL_ID_REDACTED]", "th_national_id", "NATIONAL_ID", true, false,
            list("national id", "thai id", "เลขประจำตัวประชาชน", "บัตรประชาชน", "เลขบัตร", "promptpay"),
            list(),
            list(),
            true, "th_national_id", true),
        new Pattern("id_nik", "ID", "national_id",
            "\\b\\d{16}\\b",
            "[NIK_REDACTED]", "id_nik", "NIK", true, false,
            list("nomor induk kependudukan", "kartu tanda penduduk", "dukcapil"),
            list("nik", "e-ktp", "ektp", "ktp", "npwp"),
            list(),
            false, null, false)
    ));

    /** SIGNALS is in evaluation order. Stop at the first signal a country matches. */
    public static final List<Signal> SIGNALS = Collections.unmodifiableList(Arrays.asList(
        new Signal("AU",
            "\\b\\d{3}\\s\\d{3}\\s\\d{3}\\b",
            "",
            list("tfn", "tax file", "medicare"),
            list(),
            "AU"),
        new Signal("AU",
            "\\b\\d{4}\\s\\d{5}\\s\\d{1}\\b",
            "",
            list(),
            list(),
            "AU"),
        new Signal("AU",
            "\\b(0[2-9]|\\+61)\\d{8,9}\\b",
            "",
            list("au", "australia", "australian"),
            list(),
            "AU"),
        new Signal("GB",
            "\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b",
            "i",
            list("national insurance", "ni number", "nino", "ni:"),
            list(),
            "GB"),
        new Signal("GB",
            "\\b[A-Z]{1,2}\\d{1,2}[ \\t]?\\d[A-Z]{2}\\b",
            "",
            list("uk", "united kingdom", "britain", "postcode"),
            list(),
            "GB"),
        new Signal("GB",
            "\\b(\\+44|0044)\\d{10}\\b",
            "",
            list("uk", "united kingdom", "britain"),
            list(),
            "GB"),
        new Signal("CA",
            "\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b",
            "",
            list("sin", "social insurance", "canada revenue", "cra", "employment insurance"),
            list(),
            "CA"),
        new Signal("CA",
            "\\b[A-Za-z]\\d[A-Za-z][ \\t]?\\d[A-Za-z]\\d\\b",
            "",
            list("canada", "canadian", "postal code", "province"),
            list(),
            "CA"),
        new Signal("ZA",
            "\\b\\d{13}\\b",
            "",
            list("id number", "identity number", "south africa", "sa id", "rsa", "popia", "fica"),
            list(),
            "ZA"),
        new Signal("ZA",
            "\\b(\\+27|0)[6-8]\\d{8}\\b",
            "",
            list("south africa", "za", "johannesburg", "cape town", "durban", "pretoria"),
            list(),
            "ZA"),
        new Signal("DE",
            "\\b[1-9]\\d{10}\\b",
            "",
            list("steuer", "steuernummer", "finanzamt", "tax id", "german"),
            list(),
            "DE"),
        new Signal("DE",
            "\\b(\\+49|0049)\\d{10,11}\\b",
            "",
            list("germany", "german", "deutschland", "de"),
            list(),
            "DE"),
        new Signal("NG",
            "\\b\\d{11}\\b",
            "",
            list("bvn", "nin", "bank verification", "nigeria", "nigerian"),
            list(),
            "NG"),
        new Signal("NG",
            "\\b(\\+234|0)[7-9]\\d{9}\\b",
            "",
            list("nigeria", "nigerian", "lagos", "abuja"),
            list(),
            "NG"),
        new Signal("AE",
            "\\b784[- \\t]\\d{4}[- \\t]\\d{7}[- \\t]\\d{1}\\b",
            "",
            list(),
            list(),
            "AE"),
        new Signal("AE",
            "\\b(\\+971|00971)\\d{9}\\b",
            "",
            list("uae", "emirates", "dubai", "abu dhabi"),
            list(),
            "AE"),
        new Signal("IN",
            "\\b[A-Z]{5}\\d{4}[A-Z]{1}\\b",
            "",
            list(),
            list(),
            "IN"),
        new Signal("IN",
            "\\b\\d{4}\\s\\d{4}\\s\\d{4}\\b",
            "",
            list("aadhaar", "aadhar", "india", "indian"),
            list(),
            "IN"),
        new Signal("SA",
            "\\b1\\d{9}\\b",
            "",
            list("saudi", "ksa", "riyadh", "national id", "iqama"),
            list(),
            "SA"),
        new Signal("SA",
            "\\b(\\+966|00966)\\d{9}\\b",
            "",
            list("saudi", "ksa", "riyadh"),
            list(),
            "SA"),
        new Signal("BR",
            "\\b\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}\\b",
            "",
            list("cpf", "brazil", "brasil", "brazilian"),
            list(),
            "BR"),
        new Signal("BR",
            "\\b(\\+55|0055)\\d{11}\\b",
            "",
            list("brazil", "brasil"),
            list(),
            "BR"),
        new Signal("JP",
            "\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b",
            "",
            list("my number", "individual number", "マイナンバー", "個人番号", "japan", "japanese", "日本", "tokyo", "osaka", "nagoya", "yokohama"),
            list(),
            "JP"),
        new Signal("JP",
            "\\b(\\+81|0081)[ \\t]?\\d{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b",
            "",
            list("japan", "japanese", "日本", "tokyo", "osaka"),
            list(),
            "JP"),
        new Signal("CN",
            "\\b\\d{17}[0-9Xx]\\b",
            "",
            list("resident id", "resident identity", "identity card", "id card", "身份证", "身份證", "居民身份证", "china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou"),
            list(),
            "CN"),
        new Signal("CN",
            "\\b(\\+86|0086)[ \\t]?1[3-9]\\d{9}\\b",
            "",
            list("china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou"),
            list(),
            "CN"),
        new Signal("KR",
            "\\b\\d{6}-?[1-8]\\d{6}\\b",
            "",
            list("resident registration", "resident number", "rrn", "jumin", "주민등록번호", "주민번호", "korea", "korean", "seoul", "busan", "incheon"),
            list(),
            "KR"),
        new Signal("KR",
            "\\b(\\+82|0082)[ \\t]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b",
            "",
            list("korea", "korean", "seoul", "busan", "incheon"),
            list(),
            "KR"),
        new Signal("GH",
            "\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b",
            "",
            list("ghana card", "ghanacard", "ghana", "accra", "kumasi", "nia pin", "gra tin"),
            list(),
            "GH"),
        new Signal("GH",
            "\\b(\\+233|00233)[ \\t]?\\d{9}\\b",
            "",
            list("ghana", "ghanaian", "accra", "kumasi", "tema"),
            list(),
            "GH"),
        new Signal("IT",
            "\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b",
            "",
            list("codice fiscale", "cod. fisc", "c.f.", "anagrafe tributaria", "italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino"),
            list(),
            "IT"),
        new Signal("IT",
            "\\b(\\+39|0039)[ \\t]?\\d{9,11}\\b",
            "",
            list("italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino"),
            list(),
            "IT"),
        new Signal("KE",
            "\\b[AP]\\d{9}[A-Z]\\b",
            "",
            list("kra", "itax", "tax pin", "kenya", "kenyan", "nairobi", "mombasa", "kisumu"),
            list(),
            "KE"),
        new Signal("KE",
            "\\b(\\+254|00254)[ \\t]?\\d{9}\\b",
            "",
            list("kenya", "kenyan", "nairobi", "mombasa", "kisumu"),
            list(),
            "KE"),
        new Signal("MU",
            "\\b[123578]\\d{7}\\b",
            "",
            list("mauritius", "mauritian", "port louis", "mauritius revenue", "mra tan"),
            list(),
            "MU"),
        new Signal("MU",
            "\\b(\\+230|00230)[ \\t]?\\d{7,8}\\b",
            "",
            list("mauritius", "mauritian", "port louis"),
            list(),
            "MU"),
        new Signal("MX",
            "\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b",
            "",
            list("rfc", "homoclave", "contribuyentes", "mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey"),
            list(),
            "MX"),
        new Signal("MX",
            "\\b(\\+52|0052)[ \\t]?\\d{10}\\b",
            "",
            list("mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey"),
            list(),
            "MX"),
        new Signal("MY",
            "\\b\\d{6}-\\d{2}-\\d{4}\\b",
            "",
            list("mykad", "kad pengenalan", "nric", "malaysia", "malaysian", "kuala lumpur", "johor", "penang", "putrajaya", "selangor"),
            list(),
            "MY"),
        new Signal("MY",
            "\\b\\d{12}\\b",
            "",
            list("mykad", "my kad", "kad pengenalan", "mykid"),
            list(),
            "MY"),
        new Signal("MY",
            "\\b(\\+60|0060)[ \\t]?\\d{9,10}\\b",
            "",
            list("malaysia", "malaysian", "kuala lumpur", "johor", "penang"),
            list(),
            "MY"),
        new Signal("PK",
            "\\b\\d{5}-\\d{7}-\\d\\b",
            "",
            list("cnic", "nadra", "pakistan", "pakistani", "karachi", "lahore", "islamabad", "rawalpindi", "شناختی"),
            list(),
            "PK"),
        new Signal("PK",
            "\\b\\d{13}\\b",
            "",
            list("cnic", "nadra", "شناختی"),
            list(),
            "PK"),
        new Signal("PK",
            "\\b(\\+92|0092)[ \\t]?3\\d{9}\\b",
            "",
            list("pakistan", "pakistani", "karachi", "lahore", "islamabad"),
            list(),
            "PK"),
        new Signal("SG",
            "\\b[STFGM]\\d{7}[A-Z]\\b",
            "",
            list("nric", "singpass", "cpf", "iras", "singapore", "singaporean"),
            list(),
            "SG"),
        new Signal("SG",
            "\\b(\\+65|0065)[ \\t]?[689]\\d{3}[ \\t]?\\d{4}\\b",
            "",
            list("singapore", "singaporean"),
            list(),
            "SG"),
        new Signal("TH",
            "\\b\\d-\\d{4}-\\d{5}-\\d{2}-\\d\\b",
            "",
            list("national id", "thai", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "bangkok", "promptpay"),
            list(),
            "TH"),
        new Signal("TH",
            "\\b\\d{13}\\b",
            "",
            list("thai id", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "promptpay"),
            list(),
            "TH"),
        new Signal("TH",
            "\\b(\\+66|0066)[ \\t]?\\d{9}\\b",
            "",
            list("thailand", "thai", "bangkok", "phuket", "chiang mai"),
            list(),
            "TH"),
        new Signal("ID",
            "\\b\\d{16}\\b",
            "",
            list("nomor induk kependudukan", "kartu tanda penduduk", "dukcapil"),
            list("nik", "e-ktp", "ektp", "ktp", "npwp"),
            "ID"),
        new Signal("ID",
            "\\b(\\+62|0062)[ \\t]?\\d{9,12}\\b",
            "",
            list("indonesia", "indonesian", "jakarta", "surabaya", "bandung", "medan", "bali"),
            list(),
            "ID")
    ));

    private PiiRegistry() {}
}
